### ISSUE TITLE
Company Name

### ISSUE THREAD

**Issue by frankbellocchio** [frankbellocchio/database_CIS2109#1]
Please add a name to this post and we will just pick one. I moved this information here.

First Step: 

Deliverables: At the end of this step you need to provide the “business plan” of the company that hires you. This means that you need to submit a document with a brief description of the company purpose, expected size, products, goals e.t.c.. 

Company Name: Can be anything we want. Also we need to agree on type of company.

Question1:  A product business or service business? Let's vote on this. 

My thought: Since I think we are all IS&T we should make our business a computer/technology company because it would be helpful for all involved. That is my vote.

Technology Company
Mobile (Android or iOS) ---> Apps
Desktop (Mac or Windows) --> Industry Related Software(Like MSOffice or Photoshop)
Web(Application or Website) -->
IT Services(Network, Server Support)

Let's assign everyone to add write a paragraph. We need these items below but need to agree on business type and either products or services.

Company Description:
Purpose: 
Size:
Products or Services:
About:

Details from Business Plan: Read URL Below
http://www.bplans.com/information_technology_business_plan/executive_summary_fc.php

**Comment by tuf42483** [comment]
Datafy?
