### ISSUE TITLE
Part 03 Notes

### ISSUE THREAD

**Issue by tuf42483** [frankbellocchio/database_CIS2109#11]
### (**Primary Key**, _Foreign Key_)

CUSTOMERS:
**CustomerID**, CustFirstName, CustLastName, CustAddress, CustPhone

EMPLOYEES:
**EmployeeID**, EmployeeFirstName, EmployeeLastName, EmployeeAddress, EmployeePhone, EmployeeType (1, 2), EmployeeDesc (1 = Technician, 2 = Agent)

HIRING:
_EmployeeID_, StartDate, EndDate

LOCATION:
**LocationID** (1, 2, 3), LocDesc (1 = store, 2 = residence/house, 3 = office)

DURATION:
**JobID**, _EmployeeID_, StartTime, EndTime, Duration

SCHEDULING:
**ScheduleID**, _EmployeeID_, _LocationID_, _CustomerID_, CustFirstName, CustLastName, CustAddress, CustPhone, Date, Time, _JobID_

INVOICES:
**InvoiceID**, _CustomerID_, _JobID_, InvoiceNum, InvoiceTotal, PaymentTotal, InvoiceDueDate, PaymentDate

MILEAGE:
_EmployeeID_, StartMileage, EndMileage, Date, TotalMileage ( = EndMileage - StartMileage)

COMMISSION:
_EmployeeID_, _JobID_, DurationTotal (StartTime - EndTime), TotalMileage, PayPerMile ($), PayPerHour ($), Commission ( = (DurationTotal \* PayPerHour) + (TotalMileage \* PayPerMile))

PRODUCTS:
**ProductID**, ProductName (x wire, x computer, x server), ProductType(1, 2, ... , n), ProductPrice ($), ProductStatus ("In Stock", "Sold Out")

ORDERS:
**OrderID**, _CustomerID_, OrderDate, ShippedDate

ORDER_DETAILS:
**OrderID**, **ProductID**, OrderQty

INVENTORY:
**ProductID**, ProductQty
(HAVING ProductStatus = "In Stock")

SALES:
NumProductsSold, SalesTotal ($)

**Comment by kennyle32** [comment]
Looks good, for the PKs and FKs we can make sure they're good as we start to create the ER diagrams with 1:M, M;N etc.

**Comment by tuf42483** [comment]
Yeah, the PKs and FKs aren't exact or accurate yet, just possibilities. We'll probably need to add more of each.

**Comment by tuf42483** [comment]
## **Calculating Duration**

CREATE TABLE Duration (
JobID INT PRIMARY KEY,
StartDate DATETIME NOT NULL,
EndDate DATETIME NOT NULL
);

INSERT INTO Duration (StartDate, EndDate)
VALUES( '2016-01-01 6:34:12 AM', '2016-01-01 12:45:34 PM');
INSERT INTO Duration (StartDate, EndDate)
VALUES( '2016-01-02 9:23:08 AM', '2016-01-02 5:05:37 PM');
INSERT INTO Duration (StartDate, EndDate)
VALUES( '2016-01-03 4:34:12 PM', '2016-01-03 4:55:18 PM');
INSERT INTO Duration (StartDate, EndDate)
VALUES( '2016-01-04 11:02:00 AM', '2016-01-04 2:53:21 PM');
INSERT INTO Duration (StartDate, EndDate)
VALUES( '2016-01-05 7:52:55 AM', '2016-01-05 9:08:48 AM');
INSERT INTO Duration (StartDate, EndDate)
VALUES( '2016-01-06 7:59:11 PM', '2016-01-07 1:23:11 AM');
INSERT INTO Duration (StartDate, EndDate)
VALUES( '2016-01-07 3:12:23 AM', '2016-01-07 8:02:25 PM');

SELECT *, DateDiff(second, StartDate, EndDate) AS TotalSeconds
FROM Duration;

SELECT JobID,
TotalSeconds / 3600 AS Hours,
(TotalSeconds % 3600) / 60 AS Minutes,
TotalSeconds % 60 AS Seconds
FROM ( SELECT EventID, DateDiff(second, StartDate, EndDate) AS TotalSeconds FROM Duration );
