### ISSUE TITLE
Business Plan

### ISSUE THREAD

**Issue by frankbellocchio** [frankbellocchio/database_CIS2109#2]
We should each write 1 paragraph for 8 total sections. What do you guys think? Correction. 2 x 4 = 8.

**Comment by tuf42483** [comment]
Sounds fair enough. Let's do it.

**Comment by frankbellocchio** [comment]
Ok.
1. Company Executive Summary (About Us and Technology Services Overview)
2. Marketing Costs - Market Analysis Summary
3. Products and Services
4. Competitive Comparison
5. Service and Support - Technology Used
6. Fulfillment - Company Methodology
7. Organizational Structure
8. Financial Plan - Cash Flow Projection

We should start a new issue for each of these...and everyone pick two and write a paragraph.
