### ISSUE TITLE
Competitive Comparison

### ISSUE THREAD

**Issue by tuf42483** [frankbellocchio/database_CIS2109#6]
What sets us apart from our competition?

Datafy Inc. offers service plans for many different problems from reinstallation, accidental damage, parts coverage, in-home service, etc. We also offer set-ups & installations, protection of devices and repairs. Datafy Inc. will have a 24/7 live support team that can provide you your electronic needs online, phone, and in store. Give us a call to get started!

**Comment by frankbellocchio** [comment]
Untra Corporation
Software Development, Internet Service Providers

A + L DEVELOPMENT, LLC.
Software Development, Web Design 

Salon Clouds Plus
Software Development

**Comment by frankbellocchio** [comment]
Next I will visit each website and report back.
Style
Services
