### ISSUE TITLE
Service and Support

### ISSUE THREAD

**Issue by tuf42483** [frankbellocchio/database_CIS2109#7]
Services and support we provide and the technology used.

**Comment by tuf42483** [comment]
Datafy provides repair, installation, and optimization services provided by our specially trained computer technicians, fully knowledgeable in all operating systems and devices. Our technicians will come to your store, home, or office in a company van, equipped with all the tools needed to suit your technology needs. We'll come when it's most convenient for you! Schedule an on-site visit today.

Our customer service agents are also available to chat online or take your call 24 hours a day for faster responses to provide walkthroughs and DIY tips and tricks to make the most of your tech experience.

**Comment by frankbellocchio** [comment]
sounds good.
